baseURL = "https://wilkware.github.io"
languageCode = "de-de"
title = "Wilkware GitHub Pages"
googleAnalytics = ""
disableKinds = ["taxonomy", "RSS"]

# this setting should always be set to false, otherwise it will break the section navigation bar
pluralizelisttitles = false

[params]
  author = "Wilkware"
  description = "Minimal, one page, theme for showcasing my work"
  message = "My work ..."
  hideAutoMenu = false
  year = 2025
  url = "https://wilkware.de"

[params.social]
  facebook = "http://facebook.com/heiko.wilknitz"
  xing = "http://www.xing.com/profile/Heiko_Wilknitz"
  linkedin = "https://www.linkedin.com/in/heikowilknitz"

[[menu.main]]
  name = "HOME"
  url = "https://github.com/wilkware"

